site_name: SOS

plugins:
  - search
  - offline

repo_url: https://github.com/Hassan-Ahmadi/sos
repo_name: Github Repo Link

theme:
  # icon:
    # repo: fontawesome/brands/gitlab

  name: material
  color_mode: auto
  features:
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight

  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: indigo
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - md_in_html
  - pymdownx.blocks.caption
  - attr_list

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
