# Generated by Django 5.1.6 on 2025-02-11 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_insurancecompany_insuranceplan_policyholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurances.insuranceplan'),
        ),
    ]
